# -*- coding: utf-8 -*-
"""IRIS FLOWER CLASSIFICATION

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1clHVhq1bMcbOAifyxHswu2pi5yIjjrmv
"""

# Uploading the dataset


from google.colab import files

uploaded = files.upload()

# Importing the Libraries
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import accuracy_score

# Reading the file
df = pd.read_csv('IRIS.csv')
df.head()

# Printing the top items
df.head(10)

# Printing the bottom items
df.tail()

# Printing the total number of rows and columns
df.shape

df.isnull().sum()

df.dtypes

data = df.groupby('species')
data.head()

df['species'].unique()

df.info()

plt.boxplot(df['sepal_length'])

plt.boxplot(df['sepal_width'])

plt.boxplot(df['petal_length'])

plt.boxplot(df['petal_width'])

sns.heatmap(df.corr())

sp = {'Iris-setosa':1,'Iris-versicolor':2,'Iris-virginica':3}

df.species = [sp[i] for i in df.species]

df

X = df.iloc[:,0:4]

X

y = df.iloc[:,4]

y

X_train,X_test,y_train,y_test = train_test_split(X,y,test_size = 0.33,random_state = 42)

model = LinearRegression()

model.fit(X,y)

model.score(X,y)

model.coef_

model.intercept_

y_pred = model.predict(X_test)

print("Mean Squared Error: %.2f" %np.mean((y_pred - y_test) ** 2))

